### ISSUE TITLE
How do I build and debug the Ultraschall plug-in?

### ISSUE THREAD

**Issue by 343max** [Ultraschall/ultraschall-3#14]
Hey!

I tried to build the Ultraschall plugin.

When running the `build.sh` script I get an error message:

```
⟩ ./build.sh
xcodebuild: error: The directory /Users/maxvw/Documents/ultraschall-3/REAPER/Plugin/reaper_ultraschall does not contain an Xcode project.
```

What's the correct way to build and debug Ultraschall?

**Comment by heikopanjas** [comment]
We moved to CMake some time ago. In the `3.1.1` branch change to the `ultraschall-3/REAPER/Plugin/reaper_ultraschall` directory and run 

```mkdir -p build && cd build```.

Create the required project file with 

```cmake -G Xcode ../```

and finally build the plug-in:

```cmake --build . --target reaper_ultraschall --config Debug```.

On Windows use the `Visual Studio 15 2017 Win64` generator.

**Comment by 343max** [comment]
Now I can build, great. Is there a one click solution to debug what I've build?

**Comment by 343max** [comment]
I built a debug Scheme, looks good now. Breakpoints are being hit.
